/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package PP;

import com.fancy.service.MovieService;
import com.fancy.service.impl.MovieServiceImpl;
import java.awt.Color;
import java.awt.Font;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 10637
 */
public class A3 extends javax.swing.JFrame {

    private MovieService movieservice = new MovieServiceImpl();
    private List<com.fancy.entity.Movie> movieList;
    private int row = -1;

    public A3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        movieList=movieservice.queryAllMovie();
        movietable = new javax.swing.JTable(){
            public boolean isCellEditable( int row, int column) {
                return false;
            }

        };
        serNameText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        serTypecomboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        竖版海报 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        qwe = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtrDetailtest = new javax.swing.JTextArea();
        mIdText = new javax.swing.JTextField();
        movieTypeText = new javax.swing.JTextField();
        movielangText = new javax.swing.JTextField();
        timeText = new javax.swing.JTextField();
        showtime = new javax.swing.JTextField();
        movieheng = new javax.swing.JTextField();
        moviepicadreText = new javax.swing.JTextField();
        movieshow = new javax.swing.JTextField();
        scoreText = new javax.swing.JTextField();
        mlocaText = new javax.swing.JTextField();
        movieactorText = new javax.swing.JTextField();
        movieNameText = new javax.swing.JTextField();
        del = new javax.swing.JButton();
        update = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1120, 630));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(1120, 630));
        jPanel1.setMinimumSize(new java.awt.Dimension(1120, 630));

        search.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        search.setForeground(new java.awt.Color(51, 51, 51));
        search.setText("搜索");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        movietable.setModel(new DefaultTableModel(
            new Object[][] {
            },
            new String[] {
                "电影编号", "电影名字", "语言", " 地区","海报地址","时长","类别","分数"
            }
        ) {
            boolean[] columnEditables = new boolean[] {
                false, false, false, false,false,false,false,false
            };
            public boolean isCellEditable(int row, int column) {
                return columnEditables[column];
            }
        });
        fillTable( movieList);

        DefaultTableCellRenderer r = new DefaultTableCellRenderer();
        r.setHorizontalAlignment(JLabel.CENTER);
        movietable.setDefaultRenderer(Object.class, r);
        movietable.setRowHeight(70);
        movietable.getTableHeader().setFont(new Font("楷体", 1, 20));
        movietable.getTableHeader().setBackground(Color.orange);
        movietable.getTableHeader().setReorderingAllowed(false); // 不可交换顺序
        movietable.getTableHeader().setResizingAllowed(false); // 不可拉动表格
        movietable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                movietableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(movietable);

        serNameText.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        serNameText.setForeground(new java.awt.Color(51, 51, 51));
        serNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serNameTextActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("类型：");

        serTypecomboBox.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        serTypecomboBox.setForeground(new java.awt.Color(51, 51, 51));
        serTypecomboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2D", "3D", "IMAX3D" }));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("电影名称：");

        竖版海报.setBackground(new java.awt.Color(255, 255, 255));
        竖版海报.setFont(new java.awt.Font("微软雅黑", 0, 20)); // NOI18N
        竖版海报.setForeground(new java.awt.Color(255, 255, 255));
        竖版海报.setText("竖版海报：");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("微软雅黑", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("语言：");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("微软雅黑", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("名字：");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("微软雅黑", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("时长：");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("微软雅黑", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("类别：");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("微软雅黑", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("电影简介");

        qwe.setBackground(new java.awt.Color(255, 255, 255));
        qwe.setFont(new java.awt.Font("微软雅黑", 0, 20)); // NOI18N
        qwe.setForeground(new java.awt.Color(255, 255, 255));
        qwe.setText("国家：");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("微软雅黑", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("演员：");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("微软雅黑", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("上映时间：");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("微软雅黑", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("编号：");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("微软雅黑", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("上映情况：");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("微软雅黑", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("横板海报：");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("微软雅黑", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("评分：");

        txtrDetailtest.setLineWrap(true);        //激活自动换行功能
        txtrDetailtest.setWrapStyleWord(true);            // 激活断行不断字功能
        txtrDetailtest.setColumns(20);
        txtrDetailtest.setRows(5);
        jScrollPane2.setViewportView(txtrDetailtest);

        mIdText.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        mIdText.setForeground(new java.awt.Color(51, 51, 51));
        mIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mIdTextActionPerformed(evt);
            }
        });

        movieTypeText.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        movieTypeText.setForeground(new java.awt.Color(51, 51, 51));
        movieTypeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieTypeTextActionPerformed(evt);
            }
        });

        movielangText.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        movielangText.setForeground(new java.awt.Color(51, 51, 51));
        movielangText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movielangTextActionPerformed(evt);
            }
        });

        timeText.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        timeText.setForeground(new java.awt.Color(51, 51, 51));
        timeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeTextActionPerformed(evt);
            }
        });

        showtime.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        showtime.setForeground(new java.awt.Color(51, 51, 51));
        showtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showtimeActionPerformed(evt);
            }
        });

        movieheng.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        movieheng.setForeground(new java.awt.Color(51, 51, 51));
        movieheng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moviehengActionPerformed(evt);
            }
        });

        moviepicadreText.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        moviepicadreText.setForeground(new java.awt.Color(51, 51, 51));
        moviepicadreText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moviepicadreTextActionPerformed(evt);
            }
        });

        movieshow.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        movieshow.setForeground(new java.awt.Color(51, 51, 51));
        movieshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieshowActionPerformed(evt);
            }
        });

        scoreText.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        scoreText.setForeground(new java.awt.Color(51, 51, 51));
        scoreText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreTextActionPerformed(evt);
            }
        });

        mlocaText.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        mlocaText.setForeground(new java.awt.Color(51, 51, 51));
        mlocaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlocaTextActionPerformed(evt);
            }
        });

        movieactorText.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        movieactorText.setForeground(new java.awt.Color(51, 51, 51));
        movieactorText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieactorTextActionPerformed(evt);
            }
        });

        movieNameText.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        movieNameText.setForeground(new java.awt.Color(51, 51, 51));
        movieNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieNameTextActionPerformed(evt);
            }
        });

        del.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        del.setForeground(new java.awt.Color(51, 51, 51));
        del.setText("删除");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        update.setForeground(new java.awt.Color(51, 51, 51));
        update.setText("搜索");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(51, 51, 51));
        back.setText("返回");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(serTypecomboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(search)
                .addGap(265, 265, 265))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(movieTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(timeText, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel11)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(movielangText, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(竖版海报, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(movieshow, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(movieNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(144, 144, 144)
                                        .addComponent(jLabel8))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(moviepicadreText, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(movieheng, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(showtime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(qwe, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(mlocaText, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(movieactorText, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(scoreText, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(26, 26, 26))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(del)
                                                .addGap(106, 106, 106)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(back)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(update)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search)
                    .addComponent(serNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(serTypecomboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(mIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieshow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(movielangText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(moviepicadreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(movieactorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(竖版海报)
                                .addComponent(jLabel10)
                                .addComponent(jLabel4)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mlocaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(qwe)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel14)
                                    .addComponent(movieTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(movieheng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11)
                            .addComponent(jLabel15)
                            .addComponent(timeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scoreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update)
                    .addComponent(del)
                    .addComponent(back))
                .addGap(35, 35, 35))
        );

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>

    private void serNameTextActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void mIdTextActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void movieTypeTextActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void movielangTextActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void timeTextActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void showtimeActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void moviehengActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void moviepicadreTextActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void movieshowActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void scoreTextActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void mlocaTextActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void movieactorTextActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void movieNameTextActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void movietableMousePressed(java.awt.event.MouseEvent evt) {                                        

        row = movietable.getSelectedRow();
        if (row != -1) {
            mIdText.setText(String.valueOf(movieList.get(row).getmId()));
            mlocaText.setText(movieList.get(row).getMlocality());
            movielangText.setText(movieList.get(row).getMlanguage());
            movieNameText.setText(movieList.get(row).getmName());
            moviepicadreText.setText(movieList.get(row).getmPicaddress());
            txtrDetailtest.setText(movieList.get(row).getmDetail());
            movieTypeText.setText(movieList.get(row).getmType());
            timeText.setText(String.valueOf(movieList.get(row).getmDuration()));
            scoreText.setText(String.valueOf(movieList.get(row).getmGrade()));

        } else {
            JOptionPane.showMessageDialog(null, "未选定电影");
        }
        // TODO add your handling code here:
    }                                       

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {                                       

        String mType = (String) serTypecomboBox.getSelectedItem();
        String mName = serNameText.getText();
        movieList = movieservice.queryMovieByTypeandName(mType, mName);
        
        fillTable(movieList);
        // TODO add your handling code here:
    }                                      

    private void delActionPerformed(java.awt.event.ActionEvent evt) {                                    

        if (row != -1) {
            int mId = Integer.parseInt(mIdText.getText());
            movieList.remove(row);
            if (movieservice.delMovie(mId)) {
                JOptionPane.showMessageDialog(null, "删除成功");
                fillTable(movieList);

            } else {
                JOptionPane.showMessageDialog(null, "删除失败");
                reset();
            }
        } else {
            JOptionPane.showMessageDialog(null, "请选择电影");
        }
        // TODO add your handling code here:
    }                                   

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {                                       

        if (row != -1) {
            if (judge()) {
                try {
                    int mId = Integer.parseInt(mIdText.getText());
                    int mtime = Integer.parseInt(timeText.getText());
                    String mloca = mlocaText.getText();
                    String movielang = movielangText.getText();
                    String moviepicadre = moviepicadreText.getText();
                    String movieDe = txtrDetailtest.getText();
                    String movieType = movieTypeText.getText();
                    String movieName = movieNameText.getText();
                    double mscore = Double.parseDouble(scoreText.getText());
                    
                    String mActor = movieactorText.getText();
                    String mTime = timeText.getText();
                    Date Time= new Date(mTime);
                    String mshow = movieshow.getText();
                    String mheng = movieheng.getText();
                    
                    /*
                     * movieList.get(row)=new Movie(movieName,movielang,
				 * movieloa,picaddress,detail,mtime,mType,mscore);
                     */
                    //String mName, String mActor, String mlanguage, String mlocality, String mPicaddress, String mDetail, int mDuration, String mType, double mGrade, Date mTime, String mshow, String mheng
                    com.fancy.entity.Movie movie = new com.fancy.entity.Movie(mId, movieName,mActor,movielang, mloca, moviepicadre, movieDe, mtime, movieType, mscore,Time,mshow,mheng);
                    if (movieservice.updateMovie(movie)) {
                        JOptionPane.showMessageDialog(null, "修改成功");
                    } else {
                        JOptionPane.showMessageDialog(null, "修改失败");
                    }
                    movieList = movieservice.queryAllMovie();
                    fillTable(movieList);
                    reset();
                } catch (NumberFormatException e2) {
                    // TODO: handle exception
                    JOptionPane.showMessageDialog(null, "格式错误");
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "请选择电影");
        }
        // TODO add your handling code here:
    }                                      

    private void backActionPerformed(java.awt.event.ActionEvent evt) {                                     

        new A1().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }                                    

    private void fillTable(List<com.fancy.entity.Movie> movieList2) {
        // TODO Auto-generated method stub
        DefaultTableModel dtm = (DefaultTableModel) movietable.getModel();
        dtm.setRowCount(0); // 设置成0行
        int movieRow = movieList2.size();
        for (int i = 0; i < movieRow; i++) {
            Vector v = new Vector();
            v.add(movieList2.get(i).getmId());
            v.add(movieList2.get(i).getmName());
            v.add(movieList2.get(i).getMlanguage());
            v.add(movieList2.get(i).getMlocality());
            v.add(movieList2.get(i).getmPicaddress());
            v.add(movieList2.get(i).getmDuration());
            v.add(movieList2.get(i).getmType());
            v.add(movieList2.get(i).getmGrade());
            dtm.addRow(v);
        }

    }

    public boolean judge() {
        if ("".equals(movieNameText.getText())) {
            JOptionPane.showMessageDialog(null, "电影名字不能为空");
            return false;
        }
        if ("".equals(movielangText.getText())) {
            JOptionPane.showMessageDialog(null, "电影语言不能为空");
            return false;
        }
        if ("".equals(mlocaText.getText())) {
            JOptionPane.showMessageDialog(null, "电影地址不能为空");
            return false;
        }
        if ("".equals(moviepicadreText.getText())) {
            JOptionPane.showMessageDialog(null, "海报地址不能为空");
            return false;
        }
        if ("".equals(timeText.getText())) {
            JOptionPane.showMessageDialog(null, "电影时长不能为空");
            return false;
        }
        if ("".equals(scoreText.getText())) {
            JOptionPane.showMessageDialog(null, "评分不能为空");
            return false;
        }
        if ("".equals(showtime.getText())) {
            JOptionPane.showMessageDialog(null, "电影上映时间不能为空");
            return false;
        }        
        if ("".equals(movieheng.getText())) {
            JOptionPane.showMessageDialog(null, "电影横板海报不能为空");
            return false;
        }        
        if ("".equals(movieactorText.getText())) {
            JOptionPane.showMessageDialog(null, "电影演员能为空");
            return false;
        }
        return true;
    }

    public void reset() {
        movieNameText.setText("");
        movielangText.setText("");
        mlocaText.setText("");
        moviepicadreText.setText("");
        timeText.setText("");
        scoreText.setText("");
        txtrDetailtest.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new A3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JButton back;
    private javax.swing.JButton del;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mIdText;
    private javax.swing.JTextField mlocaText;
    private javax.swing.JTextField movieNameText;
    private javax.swing.JTextField movieTypeText;
    private javax.swing.JTextField movieactorText;
    private javax.swing.JTextField movieheng;
    private javax.swing.JTextField movielangText;
    private javax.swing.JTextField moviepicadreText;
    private javax.swing.JTextField movieshow;
    private javax.swing.JTable movietable;
    private javax.swing.JLabel qwe;
    private javax.swing.JTextField scoreText;
    private javax.swing.JButton search;
    private javax.swing.JTextField serNameText;
    private javax.swing.JComboBox serTypecomboBox;
    private javax.swing.JTextField showtime;
    private javax.swing.JTextField timeText;
    private javax.swing.JTextArea txtrDetailtest;
    private javax.swing.JButton update;
    private javax.swing.JLabel 竖版海报;
    // End of variables declaration
}
